### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'playlistSidebarRenderer')

### ISSUE THREAD

**Issue by codingMASTER398** [Fabricio-191/youtube#9]
I'm seeing an increase of errors on one of my websites, [JWA](https://jwa.coding398.dev/).

When the program starts, it automatically tries to fetch around 30 YouTube playlists for the artists displayed on the site. Ever since the new YouTube redesign, 50% of the requests began to fail with the following error:
```
TypeError: Cannot read properties of undefined (reading 'playlistSidebarRenderer')
    at parsePlaylist (/home/runner/Jam-with-all/node_modules/@fabricio-191/youtube/lib/methods/playlist.js:44:19)
    at getPlaylist (/home/runner/Jam-with-all/node_modules/@fabricio-191/youtube/lib/methods/playlist.js:35:9)
    at runMicrotasks (<anonymous>)
```
Any help here?

**Comment by Fabricio-191** [comment]
Yeah, the data changed since the update, solved it on version 0.0.4, update and tell me if it reapears
